#!/bin/bash
set -e

apt-get update -y
apt-get install python3 wget unzip -y
echo "Installing Packer..."
wget https://releases.hashicorp.com/packer/1.11.2/packer_1.11.2_linux_amd64.zip
unzip packer_1.11.2_linux_amd64.zip -d /usr/local/bin
/usr/local/bin/packer version

unzip ansible.zip -d ./ansible

echo $OS_TYPE
echo $SOURCE_IMAGE_FAMILY
echo $IMAGE_NAME
echo $OS_ARCH
echo $DATE_CREATED
echo $NETWORK
echo $SUBNET

echo "Running Packer Build"

if [[ "$OS_TYPE" == "Windows" ]]
then
   PACKER_FILE="gcp_win.pkr.hcl"
elif [[ "$SOURCE_IMAGE_FAMILY" == "RHEL_9" ]]
then
   PACKER_FILE="gcp_rhel.pkr.hcl"
else 
   PACKER_FILE="gcp.pkr.hcl"
fi
#python3 snow.py

/usr/local/bin/packer init $PACKER_FILE
/usr/local/bin/packer build $PACKER_FILE

sleep 30 # wait a bit as there can be some timing issues before the amis can be queried
echo 'store_metadata.py'
python3 store_metadata.py

