steps:
# Step 1: Download the file from GCS
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gsutil cp gs://your-bucket-name/your-file.tar.gz /workspace/your-file.tar.gz

# Step 2: Extract the file
- name: 'gcr.io/cloud-builders/busybox'
  args:
  - 'tar'
  - '-xzf'
  - '/workspace/your-file.tar.gz'
  - '-C'
  - '/workspace'

# Step 3: Run the script
- name: 'gcr.io/cloud-builders/bash'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    cd /workspace/your-extracted-folder
    ./your-script.sh
