steps:
  # Build and publish the Packer image using Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t', 'gcr.io/$PROJECT_ID/packer:${_PACKER_VERSION}',
      '-t', 'gcr.io/$PROJECT_ID/packer',
      '--build-arg', 'PACKER_VERSION=${_PACKER_VERSION}',
      '--build-arg', 'PACKER_VERSION_SHA256SUM=${_PACKER_VERSION_SHA256SUM}',
      '.'
    ]

  # Use Packer to initialize and build the golden image
  - name: 'gcr.io/$PROJECT_ID/packer'
    args:
    - init
    - packer.pkr.hcl
  
  - name: 'gcr.io/$PROJECT_ID/packer'
    args:
    - build
    - packer.pkr.hcl

substitutions:
  _PACKER_VERSION: 1.9.1
  _PACKER_VERSION_SHA256SUM: 793ed62255b9e572eda0c77d2a770f5fde501314b7598320786f1e51feb260d6

images:
  - 'gcr.io/$PROJECT_ID/packer:latest'
  - 'gcr.io/$PROJECT_ID/packer:${_PACKER_VERSION}'

tags: ['cloud-builders-community']
