steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'run-packer'
    entrypoint: 'bash'
    args: ['-c', './execute_packer.sh']
    env:
      - 'SOURCE_IMAGE_FAMILY=${_SOURCE_IMAGE_FAMILY}'
      - 'SSH_USERNAME=${_SSH_USERNAME}'
      - 'ARCHITECTURE=${_ARCHITECTURE}'
      # Terraform outputs
      - 'PROJECT_ID=${_PROJECT_ID}'
      
timeout: '3600s'  # Optional, set timeout for the build
        
