#!/bin/bash

# Download the gsutil tar.gz
curl -O https://storage.googleapis.com/downloads.cloud.google.com/public/gsutil.tar.gz

# Extract the tar.gz file
tar -xvf gsutil.tar.gz

# Move gsutil to a directory in your PATH (optional)
sudo mv gsutil /usr/local/bin/

# Verify installation
gsutil version
