name: Common Setup

on:
  workflow_call:
    inputs:
      packer_file:
        description: "Path to the Packer configuration file"
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      id-token: 'write'
      contents: 'read'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Authentication
        id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: 'prj-ospacker-useast-dev-23295'
          service_account: 'sa-ospacker-us-4002@prj-ospacker-useast-dev-23295.iam.gserviceaccount.com'
          workload_identity_provider: 'projects/463003052712/locations/global/workloadIdentityPools/wif-pool/providers/wif-provider'

      - name: Setup HashiCorp Packer
        uses: hashicorp/setup-packer@v3.0.0

      - name: Init Packer
        run: packer init ${{ inputs.packer_file }}

      - name: Run Packer Build
        run: packer build ${{ inputs.packer_file }}
