name: OS Packer Pipeline

on:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-rhel:
    uses: ./.github/workflows/common-setup.yml  # Reusable workflow
    steps:
      - name: Run Packer for RHEL
        run: packer build gcp-rhel.pkr.hcl  # Build the RHEL configuration

  build-ubuntu:
    uses: ./.github/workflows/common-setup.yml  # Reusable workflow
    steps:
      - name: Run Packer for Ubuntu
        run: packer build gcp-ubuntu.pkr.hcl  # Build the Ubuntu configuration

  build-windows:
    uses: ./.github/workflows/common-setup.yml  # Reusable workflow
    steps:
      - name: Run Packer for Windows
        run: packer build gcp-win.pkr.hcl  # Build the Windows configuration

  build-sql:
    uses: ./.github/workflows/common-setup.yml  # Reusable workflow
    steps:
      - name: Run Packer for SQL
        run: packer build gcp-sql.pkr.hcl  # Build the SQL configuration
