name: OS Packer Pipeline

on:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-rhel:
    uses: ./.github/workflows/common-setup.yml
    with:
      packer_file: gcp-rhel.pkr.hcl

  build-ubuntu:
    uses: ./.github/workflows/common-setup.yml
    with:
      packer_file: gcp-ubuntu.pkr.hcl

  build-windows:
    uses: ./.github/workflows/common-setup.yml
    with:
      packer_file: gcp-win.pkr.hcl

  build-sql:
    uses: ./.github/workflows/common-setup.yml
    with:
      packer_file: gcp-sql.pkr.hcl

  cleanup-old-images:
    runs-on: ubuntu-latest
    needs: [build-rhel, build-ubuntu, build-windows, build-sql]  # Ensure this job runs after all packer builds
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-cloud-compute

      - name: Authenticate with GCP
        run: gcloud auth activate-service-account --key-file=${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Run the Python script to cleanup old images
        run: python cleanup_old_images.py  # Replace with your actual script name
