name: CI

on:
  schedule:
    - cron: '0 0 1 * *'  # Runs at 12:00 AM UTC on the 1st of every month
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Authentication 
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'prj-ospacker-useast-dev-23295'
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
    
      - name: Setup HashiCorp Packer
        uses: hashicorp/setup-packer@v3.0.0
	
      - name: Run Packer for RHEL
        run: |
          packer build gcp-rhel.pkr.hcl      

      - name: Run Packer for Ubuntu
        run: |
          packer build gcp-ubuntu.pkr.hcl
	  
      - name: Run Packer for Windows
        run: |
          packer build gcp-win.pkr.hcl

      - name: Run Packer for SQL
        run: |
          packer build gcp-sql.pkr.hcl
