name: Run Packer Monthly

on:
  schedule:
    - cron: '0 0 1 * *'  # Runs at 12:00 AM UTC on the 1st of every month
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Packer (Packer is automatically installed)
      - name: Set up Packer
        uses: hashicorp/setup-packer@v1

      # Run Packer for Ubuntu
      - name: Run Packer for Ubuntu
        run: |
          packer build packer-ubuntu.hcl

      # Run Packer for CentOS
      - name: Run Packer for CentOS
        run: |
          packer build packer-sql.hcl

      # Run Packer for Windows
      - name: Run Packer for Windows
        run: |
          packer build packer-windows.hcl

      # Run Packer for RHEL
      - name: Run Packer for RHEL
        run: |
          packer build packer-rhel.hcl
