name: OS Packer Pipeline

on:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-rhel:
    uses: ./.github/workflows/common-setup.yml
    with:
      packer_file: gcp-rhel.pkr.hcl

  build-ubuntu:
    uses: ./.github/workflows/common-setup.yml
    with:
      packer_file: gcp-ubuntu.pkr.hcl

  build-windows:
    uses: ./.github/workflows/common-setup.yml
    with:
      packer_file: gcp-win.pkr.hcl

  build-sql:
    uses: ./.github/workflows/common-setup.yml
    with:
      packer_file: gcp-sql.pkr.hcl
