name: Wiz Security Scan

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      image_name:
        required: true
        type: string

jobs:
  wiz-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Wiz CLI
        run: curl -o wizcli https://downloads.wiz.io/wizcli/latest/wizcli-linux-amd64 && chmod +x wizcli

      - name: Authenticate to Wiz
        run: ./wizcli auth --id "$WIZ_CLIENT_ID" --secret "$WIZ_CLIENT_SECRET"
        env:
          WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
          WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}

      - name: Run Wiz CLI Scan for ${{ inputs.os }}
        run: |
          echo "Scanning Image: ${{ inputs.image_name }}"
          ./wizcli vm-image scan --id ${{ inputs.image_name }} --subscriptionId prj-ospacker-useast-dev-23295 --region us-east4 -p "$WIZ_IAC_POLICY" --tag github_action_run_id=${{ github.run_id }} -o results-${{ inputs.os }}.sarif,sarif,false
        env:
          WIZ_IAC_POLICY: "Default vulnerabilities policy"

      - name: Upload Wiz Scan Results
        uses: actions/upload-artifact@v3
        with:
          name: wiz-scan-results-${{ inputs.os }}
          path: results-${{ inputs.os }}.sarif
