name: Share data between jobs

on: [push]

jobs:
  job_1:
    name: Add 3 and 7
    runs-on: actions_runner_dev
    steps:
      - shell: bash
        run: |
          expr 3 + 7 > math-homework.txt
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v4
        with:
          name: homework1
          path: math-homework.txt

  job_2:
    name: Multiply by 9
    needs: job_1
    runs-on: actions_runner_dev
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v4
        with:
          name: homework1
      - shell: bash
        run: |
          value=`cat math-homework.txt`
          expr $value \* 9 > math-homework.txt
      - name: Upload math result for job 2
        uses: actions/upload-artifact@v4
        with:
          name: homework2
          path: math-homework.txt

  job_3:
    name: Display results
    needs: job_2
    runs-on: actions_runner_dev
    steps:
      - name: Download math result for job 2
        uses: actions/download-artifact@v4
        with:
          name: homework2
      - name: Print the final result
        shell: bash
        run: |
          value=`cat math-homework.txt`
          echo The result is $value
